INSERT INTO TICKET VALUES (1,'unchecked');
INSERT INTO TICKET VALUES (2,'unchecked');
INSERT INTO TICKET VALUES (3,'unchecked');


INSERT INTO TICKET_LINES  VALUES (1,1,0,1,3,1);
INSERT INTO TICKET_LINES  VALUES (2,1,0,1,3,2);
INSERT INTO TICKET_LINES  VALUES (3,1,0,1,3,2);
INSERT INTO TICKET_LINES  VALUES (4,1,0,1,3,3);